version: '3.9'

services:
  web:
    build:
      context: ./backend
    container_name: crm_web
    command: gunicorn CRM.wsgi:application --bind 0.0.0.0:8000
    env_file: .env.staging
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: crm_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web

  db:
    image: mysql:8.0
    container_name: crm_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: crm
      MYSQL_USER: crmuser
      MYSQL_PASSWORD: crmpass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
  static_volume: