version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:3306 --
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn CRM.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:7

volumes:
  mysql_data: