name: Django CI

# Trigger this workflow on pushes or pull requests to the 'main' branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
# 1. Build, Lint, Test (CI Phase)
  build:
    runs-on: ubuntu-latest

    services:
    # Spin up a MySQL service for Django to use during tests
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h127.0.0.1 -uroot -p$rootpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v4
      
       # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

         # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


     # Code Quality Checks (Linting, Formatting, Typing, Security)
    - name: Run Flake8 for linting
      continue-on-error: true
      run: |
        pip install flake8
        flake8 .
  
    - name: Run Black for code formatting check
      continue-on-error: true
      run: |
        pip install black
        black --check .

    - name: Run Mypy for type checking
      continue-on-error: true
      run: |
        pip install mypy
        mypy .

    - name: Run Bandit for security checks
      continue-on-error: true
      run: |
        pip install bandit
        bandit -r .    

      # wait for db
    - name: Wait for MySQL
      run: |
        for i in {1..15}; do
          if mysqladmin ping -h127.0.0.1 -uroot  -p${{ secrets.MYSQL_ROOT_PASSWORD }} ; then
            echo "MySQL is up!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 5
        done
        
    # Run Django database migrations and unit tests
    - name: Run Migrations and Tests
      env:
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.MYSQL_DATABASE }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput
        python manage.py test

     # Email Job status
    - name: Send email on failure
      if: false    # ensures this runs even if previous steps fail
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            [${{ job.status }}] CI/CD Pipeline - ${{ github.repository }}
          to: ${{ secrets.EMAIL_RECIPIENTS }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            GitHub Actions CI/CD Workflow: ${{ github.workflow }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Job: ${{ github.job }}
            Status: ${{ job.status }}
  
            View run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
    # Docker Image Build and Push (CD Phase)
  docker:
    needs: build   # Only run this after build job succeeds
    runs-on: ubuntu-latest

    steps:
        # Checkout code again
    - name: Checkout code
      uses: actions/checkout@v4

    #Get changed files
    - name: Get changed files
      id: changes
      uses: tj-actions/changed-files@v44

    - name: Check if app-related files changed
      id: should_build
      run: |
        echo "Checking for relevant file changes..."

        files_changed="${{ steps.changes.outputs.all_changed_files }}"
        echo "Files changed: $files_changed"

        should_build="false"
        for file in $files_changed; do
          if [[ "$file" =~ ^(Dockerfile|src/|app/|backend/|frontend/|package.json|requirements.txt|prisma/|services/).* ]]; then
            should_build="true"
            break
          fi
        done

        echo "SHOULD_BUILD=$should_build" >> $GITHUB_ENV

    - name: Stop if no relevant files changed
      if: env.SHOULD_BUILD != 'true'
      run: |
          echo "No application code changes detected. Skipping Docker image build."
          exit 0

       # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

       # Log in to DockerHub using GitHub Secrets
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     # Set image tags (latest, versioned, and commit SHA)
    - name: Define Image Tags
      id: vars
      run: |
       echo "VERSION=v1" >> $GITHUB_ENV
       echo "IMAGE_TAGS=${{ secrets.DOCKER_USERNAME }}/crm-web:latest,${{ secrets.DOCKER_USERNAME }}/crm-web:v1,${{ secrets.DOCKER_USERNAME }}/crm-web:${{ github.sha }}" >> $GITHUB_ENV
   
      # Build and push multi-arch Docker image to DockerHub
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.IMAGE_TAGS }}
         

        #  Email Job status
    - name: Send email notification
      if: false  
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: >
         [${{ job.status }}] CI/CD Pipeline - ${{ github.repository }}
        to: ${{ secrets.EMAIL_RECIPIENTS }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          GitHub Actions CI/CD Workflow: ${{ github.workflow }}
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Job: ${{ github.job }}
          Status: ${{ job.status }}

          View run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}    
      